### ISSUE TITLE
photo upload broken

### ISSUE THREAD

**Issue by eunicekokor** [adicu/eventum#110]
when uploading new photo for event, opened up https://adicu.com/admin/posts/new instead of upload window. 
~~same error does not occur when uploading on the Media section, but I do get a Internal Service Error when trying to upload a new picture.~~

**Comment by natebrennand** [comment]
bump. this still seems to be broken (at least the upload button on the new blog post form)

**Comment by natebrennand** [comment]
oops, this is functioning, but the error message is bad. opening a clarifying ticker
