### ISSUE TITLE
[CLOSED] New adicu.com blog post can't save/escape when in full screen view

### ISSUE THREAD

**Issue by danrschlosser** [adicu/eventum#51]
<a href="https://github.com/gleanawa"><img src="https://avatars.githubusercontent.com/u/5566619?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gleanawa](https://github.com/gleanawa)**
_Monday Sep 15, 2014 at 00:28 GMT_
_Originally opened as https://github.com/danrschlosser/eventum/issues/51_

----

**Comment by danrschlosser** [comment]
<a href="https://github.com/danrschlosser"><img src="https://avatars.githubusercontent.com/u/2433509?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [danrschlosser](https://github.com/danrschlosser)**
_Monday Sep 15, 2014 at 05:18 GMT_

----

Short term solution:  The ESC button will exit fullscreen mode.  




Medium term:  put a freakin close button (lol)

**Comment by danrschlosser** [comment]
<a href="https://github.com/danrschlosser"><img src="https://avatars.githubusercontent.com/u/2433509?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [danrschlosser](https://github.com/danrschlosser)**
_Sunday Sep 21, 2014 at 15:35 GMT_

----

@natebrennand @gleanawa So the editor hides these buttons in full screen because you can press ESC to close the fullscreen.  Adding a close fullscreen button would be fairly hack-y might be nice.  Should I add the button?

**Comment by danrschlosser** [comment]
<a href="https://github.com/natebrennand"><img src="https://avatars.githubusercontent.com/u/2801090?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [natebrennand](https://github.com/natebrennand)**
_Sunday Sep 21, 2014 at 15:38 GMT_

----

i would vote for no further complexity and having people figure out how to use the ESC key
(maybe put a note in the default text for a post?)

**Comment by danrschlosser** [comment]
<a href="https://github.com/gleanawa"><img src="https://avatars.githubusercontent.com/u/5566619?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gleanawa](https://github.com/gleanawa)**
_Sunday Sep 21, 2014 at 15:40 GMT_

----

I agree with Nate. That sounds good to me!

**Comment by natebrennand** [comment]
was this ever resolved?
