### ISSUE TITLE
[CLOSED] Change the footer to reference ADI labs

### ISSUE THREAD

**Issue by danrschlosser** [adicu/eventum#53]
<a href="https://github.com/danrschlosser"><img src="https://avatars.githubusercontent.com/u/2433509?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [danrschlosser](https://github.com/danrschlosser)**
_Monday Sep 15, 2014 at 05:41 GMT_
_Originally opened as https://github.com/danrschlosser/eventum/pull/53_

----

![screen shot 2014-09-15 at 1 40 29 am](https://cloud.githubusercontent.com/assets/2433509/4267386/eb0be214-3c9a-11e4-8857-6e1320416fc0.png)

----

_**[danrschlosser](https://github.com/danrschlosser)** included the following code: https://github.com/danrschlosser/eventum/pull/53/commits_

**Comment by danrschlosser** [comment]
<a href="https://github.com/danrschlosser"><img src="https://avatars.githubusercontent.com/u/2433509?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [danrschlosser](https://github.com/danrschlosser)**
_Monday Sep 15, 2014 at 05:42 GMT_

----

@natebrennand

**Comment by danrschlosser** [comment]
<a href="https://github.com/natebrennand"><img src="https://avatars.githubusercontent.com/u/2801090?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [natebrennand](https://github.com/natebrennand)**
_Monday Sep 15, 2014 at 05:44 GMT_

----

:+1:

**Comment by natebrennand** [comment]
this was also merged
