### ISSUE TITLE
[CLOSED] Many many bugfix

### ISSUE THREAD

**Issue by danrschlosser** [adicu/eventum#58]
<a href="https://github.com/danrschlosser"><img src="https://avatars.githubusercontent.com/u/2433509?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [danrschlosser](https://github.com/danrschlosser)**
_Sunday Sep 21, 2014 at 02:33 GMT_
_Originally opened as https://github.com/danrschlosser/eventum/pull/58_

----

- closes #43 
- Facebook URL field no longer manditory
- Google Calendar errors now render as a toast, instead of internal server erroring
- fix a few logical bugs for what events show up where

----

_**[danrschlosser](https://github.com/danrschlosser)** included the following code: https://github.com/danrschlosser/eventum/pull/58/commits_

**Comment by danrschlosser** [comment]
<a href="https://github.com/danrschlosser"><img src="https://avatars.githubusercontent.com/u/2433509?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [danrschlosser](https://github.com/danrschlosser)**
_Sunday Sep 21, 2014 at 02:33 GMT_

----

assign: @natebrennand

**Comment by natebrennand** [comment]
this seems to have been merged?
